version: "3.8"

services:
  mysql-db:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: studentdb
      MYSQL_USER: studentuser
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "-h", "localhost", "-uroot", "-prootpassword", "version"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  student-app-1:
    container_name: student-app-1
    image: student:v3
    build:
      context: .
    ports:
      - "8081:8282"
    environment:
      DB_URL: jdbc:mysql://mysql-container/studentdb
      DB_USERNAME: studentuser
      DB_PASSWORD: password
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network

  student-app-2:
    container_name: student-app-2
    image: student:v3
    build:
      context: .
    ports:
      - "8082:8282"
    environment:
      DB_URL: jdbc:mysql://mysql-container/studentdb
      DB_USERNAME: studentuser
      DB_PASSWORD: password
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - mysql-db
      - student-app-1
      - student-app-2

networks:
  app-network:
    name: app-network
    driver: bridge
