replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.25"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

labels:
  app: demo

env:
  - name: VERSION
    value: "v1"

rollout:
  blueGreen:
    autoPromotionEnabled: true
    autoPromotionSeconds: 300
