apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configmap
  namespace: {{ .Values.namespace }}
data:
  DB_NAME: {{ .Values.db.name }}
  DB_USERNAME: {{ .Values.db.username }}
  DB_HOST: {{ .Values.mysql.host }}
