apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-file
  namespace: student-api-ns
data:
  mysql.sql: |
    -- Add the content of your `mysql.sql` file here
    USE studentdb;
    CREATE TABLE `student` (
      `id` bigint NOT NULL AUTO_INCREMENT,
      `name` varchar(255) NOT NULL,
      `email` varchar(255) NOT NULL,
      `course` varchar(255) NOT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `email` (`email`)
    );
    INSERT INTO `student` VALUES
      (1,'John Doe','john.doe@example.com','Mathematics'),
      (2,'Jane Smith','jane.smith@example.com','Computer Science'),
      (3,'Alice Brown','alice.brown@example.com','Physics');
