apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  MYSQL_DATABASE: {{ .Values.mysql.database }}
  MYSQL_USER: {{ .Values.mysql.user }}
