apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secretstore-app
spec:
  destination:
    name: ''
    namespace: student-api-ns
    server: https://kubernetes.default.svc
  source:
    path: helm-chart/secret-store
    repoURL: https://github.com/suyogpatil-system/student-app.git
    targetRevision: CI-CD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
