apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secrectstore-vault-backend
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      version: {{ .Values.vault.version }}
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
