name: Docker Image CI

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

env:
  IMAGE_NAME: student-app

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit_hash.outputs.commit_hash }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build API
      run: make build

    - name: Run Tests
      run: make test

    - name: Get commit hash
      id: get_commit_hash
      run: |
        commit_hash=$(git rev-parse --short HEAD)
        echo "commit_hash=$commit_hash" >> $GITHUB_ENV
        echo "commit_hash=$commit_hash" >> $GITHUB_OUTPUT

  docker_build_and_push:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug commit hash
      run: echo "Commit hash: ${{ needs.build_and_test.outputs.commit_hash }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build_and_test.outputs.commit_hash || 'latest' }}
